# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: p4/server/v1/config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19p4/server/v1/config.proto\x12\x0cp4.server.v1\"E\n\nSetRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\x04\x12$\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x14.p4.server.v1.Config\"\r\n\x0bSetResponse\"\x1f\n\nGetRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\x04\"3\n\x0bGetResponse\x12$\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x14.p4.server.v1.Config\"4\n\x06\x43onfig\x12*\n\x06stream\x18\x01 \x01(\x0b\x32\x1a.p4.server.v1.StreamConfig\"\x97\x01\n\x0cStreamConfig\x12G\n\x0f\x65rror_reporting\x18\x01 \x01(\x0e\x32..p4.server.v1.StreamConfig.ErrorReportingLevel\">\n\x13\x45rrorReportingLevel\x12\x0c\n\x08\x44ISABLED\x10\x00\x12\x0b\n\x07\x45NABLED\x10\x01\x12\x0c\n\x08\x44\x45TAILED\x10\x02\x32\x86\x01\n\x0cServerConfig\x12:\n\x03Set\x12\x18.p4.server.v1.SetRequest\x1a\x19.p4.server.v1.SetResponse\x12:\n\x03Get\x12\x18.p4.server.v1.GetRequest\x1a\x19.p4.server.v1.GetResponseb\x06proto3')



_SETREQUEST = DESCRIPTOR.message_types_by_name['SetRequest']
_SETRESPONSE = DESCRIPTOR.message_types_by_name['SetResponse']
_GETREQUEST = DESCRIPTOR.message_types_by_name['GetRequest']
_GETRESPONSE = DESCRIPTOR.message_types_by_name['GetResponse']
_CONFIG = DESCRIPTOR.message_types_by_name['Config']
_STREAMCONFIG = DESCRIPTOR.message_types_by_name['StreamConfig']
_STREAMCONFIG_ERRORREPORTINGLEVEL = _STREAMCONFIG.enum_types_by_name['ErrorReportingLevel']
SetRequest = _reflection.GeneratedProtocolMessageType('SetRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETREQUEST,
  '__module__' : 'p4.server.v1.config_pb2'
  # @@protoc_insertion_point(class_scope:p4.server.v1.SetRequest)
  })
_sym_db.RegisterMessage(SetRequest)

SetResponse = _reflection.GeneratedProtocolMessageType('SetResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETRESPONSE,
  '__module__' : 'p4.server.v1.config_pb2'
  # @@protoc_insertion_point(class_scope:p4.server.v1.SetResponse)
  })
_sym_db.RegisterMessage(SetResponse)

GetRequest = _reflection.GeneratedProtocolMessageType('GetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETREQUEST,
  '__module__' : 'p4.server.v1.config_pb2'
  # @@protoc_insertion_point(class_scope:p4.server.v1.GetRequest)
  })
_sym_db.RegisterMessage(GetRequest)

GetResponse = _reflection.GeneratedProtocolMessageType('GetResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETRESPONSE,
  '__module__' : 'p4.server.v1.config_pb2'
  # @@protoc_insertion_point(class_scope:p4.server.v1.GetResponse)
  })
_sym_db.RegisterMessage(GetResponse)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'p4.server.v1.config_pb2'
  # @@protoc_insertion_point(class_scope:p4.server.v1.Config)
  })
_sym_db.RegisterMessage(Config)

StreamConfig = _reflection.GeneratedProtocolMessageType('StreamConfig', (_message.Message,), {
  'DESCRIPTOR' : _STREAMCONFIG,
  '__module__' : 'p4.server.v1.config_pb2'
  # @@protoc_insertion_point(class_scope:p4.server.v1.StreamConfig)
  })
_sym_db.RegisterMessage(StreamConfig)

_SERVERCONFIG = DESCRIPTOR.services_by_name['ServerConfig']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETREQUEST._serialized_start=43
  _SETREQUEST._serialized_end=112
  _SETRESPONSE._serialized_start=114
  _SETRESPONSE._serialized_end=127
  _GETREQUEST._serialized_start=129
  _GETREQUEST._serialized_end=160
  _GETRESPONSE._serialized_start=162
  _GETRESPONSE._serialized_end=213
  _CONFIG._serialized_start=215
  _CONFIG._serialized_end=267
  _STREAMCONFIG._serialized_start=270
  _STREAMCONFIG._serialized_end=421
  _STREAMCONFIG_ERRORREPORTINGLEVEL._serialized_start=359
  _STREAMCONFIG_ERRORREPORTINGLEVEL._serialized_end=421
  _SERVERCONFIG._serialized_start=424
  _SERVERCONFIG._serialized_end=558
# @@protoc_insertion_point(module_scope)
